trigger:
- main
variables:
 buildConfiguration: 'Release'
stages:
  - stage: Build_Backend
    jobs:
      - job: Backend
        pool:
          vmimage: windows-latest
        steps:
        - task: NuGetToolInstaller@1
          inputs:
            versionSpec: 
        - task: NuGetCommand@2
          displayName: 'NuGet Restore'
          inputs:
            command: 'restore'
            restoreSolution: '**/*.sln'
        - task: DotNetCoreCLI@2
          displayName: 'Dotnet Restore '
          inputs:
            command: 'restore'
            projects: '**/*.sln'
        - task: DotNetCoreCLI@2
          displayName: 'Dotnet Build'
          inputs:
            command: 'build'
            projects: '**/*.sln'
            arguments: '--no-restore --configuration Release'
        # - task: CopyFiles@2
        #   inputs:
        #     Contents: '**'
        #     TargetFolder: '$(Build.SourcesDirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.SourcesDirectory)'
            ArtifactName: 'Backend'
            publishLocation: 'Container'
  - stage: 
    jobs:
      - job: Frontend
        pool:
          vmimage: ubuntu-latest
        steps:
        - task: NodeTool@0
          displayName: 'install NodeJS'
          inputs:
            versionSpec: '16.x'
        - task: Npm@1
          displayName: 'Angular CLI'
          inputs:
            command: 'custom'
            customCommand: 'install @angular/cli -g'
        - task: Npm@1
          displayName: 'Npm install'
          inputs:
            command: 'install'
            workingDir: 'QuickApp/ClientApp'
        - task: Npm@1
          displayName: 'Npm Build'
          inputs:
            command: 'custom'
            workingDir: 'QuickApp/ClientApp/'
            customCommand: 'run build'
        - task: CopyFiles@2
          inputs:
            Contents: '**'
            TargetFolder: '$(Build.SourcesDirectory)/dist'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.SourcesDirectory)/dist'
            ArtifactName: 'Frontend'
            publishLocation: 'Container'
  # - stage: 
  #   jobs:
  #     - job: Build_installer_job
  #       pool:
  #         name: my-private
  #       steps:
  #       - checkout: self
  #         clean: true
  #       - task: DownloadPipelineArtifact@2
  #         inputs:
  #          buildType: 'current'
  #          targetPath: '$(Build.ArtifactStagingDirectory)'
