trigger:
- main
variables:
 buildConfiguration: 'Release'
stages:
  - stage: Build
    jobs:
      - job: Fortend
        pool:
          vmImage: ubuntu-latest
        steps:
        - task: NodeTool@0
          displayName: 'install NodeJS'
          inputs:
            versionSpec: '16.x'
        - task: Npm@1
          displayName: 'Angular CLI'
          inputs:
            command: 'custom'
            customCommand: 'npm install @angular/cli -g'
            
        - task: Npm@1
          displayName: 'Npm install'
          inputs:
            command: 'install'
        - task: Npm@1
          displayName: 'Npm Build'
          inputs:
            command: 'custom'
            workingDir: 'QuickApp/ClientApp/'
            customCommand: 'run build'
