trigger:
- main
variables:
 buildConfiguration: 'Release'
stages:
  - stage: Build
    jobs:
      - job: Fortend
        pool:
          vmImage: ubuntu-latest
        steps:
        - task: NodeTool@0
          displayName: 'install NodeJS'
          inputs:
            versionSpec: '16.x'
        - task: Cache@2
          inputs:
        - task: Npm@1
          displayName: 'Angular CLI'
          inputs:
            command: 'custom'
            customCommand: 'install @angular/cli@2.0.1'
            
        - task: Npm@1
          displayName: 'Npm install'
          inputs:
            command: 'install'
        - task: Npm@1
          displayName: 'Build Angular app'
          inputs:
            command: 'custom'
            customCommand: 'run build'
        - task: Npm@1
          displayName: 'Test Angular app'
          inputs:
            command: 'custom'
            customCommand: 'run test'
        - task: Npm@1
          displayName: 'e2e angular app'
          inputs:
            command: 'custom'
            customCommand: 'run e2e'
