trigger:
- main
variables:
 buildConfiguration: 'Release'
stages:
  - stage: Build
    jobs:
      - job: Backend
        pool:
          vmimage: ubuntu-latest
        steps:
        - task: NuGetToolInstaller@1
          inputs:
            versionSpec: 
        - task: NuGetCommand@2
          displayName: 'NuGet Restore'
          inputs:
            command: 'restore'
            restoreSolution: '**/*.sln'
        - task: DotNetCoreCLI@2
          displayName: 'Dotnet Restore '
          inputs:
            command: 'restore'
            projects: '**/*.sln'
        - task: DotNetCoreCLI@2
          displayName: 'Dotnet Build'
          inputs:
            command: 'build'
            projects: '**/*.sln'
            arguments: '--no-restore --configuration Release'
        - task: CopyFiles@2
          inputs:
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
      - job: Fortend
        pool:
          vmImage: ubuntu-latest
        steps:
        - task: NodeTool@0
          displayName: 'install NodeJS'
          inputs:
            versionSpec: '16.x'
        - task: Npm@1
          displayName: 'Angular CLI'
          inputs:
            command: 'custom'
            customCommand: 'install @angular/cli -g'
            
        - task: Npm@1
          displayName: 'Npm install'
          inputs:
            command: 'install'
            workingDir: 'QuickApp/ClientApp'
        - task: Npm@1
          displayName: 'Npm Build'
          inputs:
            command: 'custom'
            workingDir: 'QuickApp/ClientApp/'
            customCommand: 'run build'
        - task: Npm@1
          displayName: 'Npm test'
          inputs:
            command: 'custom'
            workingDir: 'QuickApp/ClientApp/'
            customCommand: 'run test'
        - task: Npm@1
          displayName: "Npm e2e"
          inputs:
            command: 'custom'
            workingDir: 'QuickApp/ClientApp/'
            customCommand: 'run e2e'